version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # JNLP agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - jenkins
    networks:
      - jenkins-net

  agent1:
    build: ./agents
    container_name: agent1
    restart: unless-stopped
    ports:
      - "2222:22"  # SSH port for testing
    networks:
      - jenkins-net

  agent2:
    build: ./agents
    container_name: agent2
    restart: unless-stopped
    ports:
      - "2223:22"
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
