version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    environment:
      - AGENT_HOSTS=agent1 agent2
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - agent1
      - agent2
    networks:
      - jenkins_net

  agent1:
    image: ubuntu:22.04
    container_name: agent1
    command: sleep infinity
    tty: true
    networks:
      - jenkins_net

  agent2:
    image: ubuntu:22.04
    container_name: agent2
    command: sleep infinity
    tty: true
    networks:
      - jenkins_net

networks:
  jenkins_net:

volumes:
  jenkins_home:
