services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    environment:
      - DOCKER_NETWORK=jenkins_net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  agent1:
    image: jenkins/ssh-agent
    container_name: agent1
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3...
    networks:
      - jenkins_net

  agent2:
    image: jenkins/ssh-agent
    container_name: agent2
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3...
    networks:
      - jenkins_net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
