FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y     openssh-client     docker.io     && rm -rf /var/lib/apt/lists/*

USER jenkins
COPY init-ssh-autoscan.sh /usr/local/bin/init-ssh-autoscan.sh
RUN chmod +x /usr/local/bin/init-ssh-autoscan.sh
ENTRYPOINT ["/usr/local/bin/init-ssh-autoscan.sh"]
